// Host emulation of the device kernels: runs a block's 256 threads as real
// threads against a std::barrier, so __syncthreads and __shared__ behave the
// way they do on a GPU. The kernel text is #included verbatim from the .hip,
// so this checks the code that actually ships, not a transcription of it.
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <thread>
#include <barrier>
#include <vector>

#define TILE 16
struct dim3i { int x, y, z; };
static thread_local dim3i threadIdx_, blockIdx_;
#define threadIdx threadIdx_
#define blockIdx  blockIdx_
#define __global__
#define __device__
#define __forceinline__ inline
// alignas leads, so that `__shared__ __align__(16) float x[]` expands to a
// well-formed declaration; the explicit attribute then has nothing left to do.
#define __shared__ alignas(16) static
#define __align__(n)
#define __launch_bounds__(...)
struct float4 { float x, y, z, w; };
static std::barrier<> *g_bar = nullptr;
#define __syncthreads() g_bar->arrive_and_wait()

#include "kern.inc"   // generated by verify.sh from darknet_kernels.hip

typedef void (*kern_t)(int,int,int,int,int,float,const float*,int,const float*,int,float,float*,int);

static void run(kern_t k, int gx, int gy, int TA,int TB,int M,int N,int K,float AL,
                const float*A,int lda,const float*B,int ldb,float BE,float*C,int ldc) {
    for (int by = 0; by < gy; ++by) for (int bx = 0; bx < gx; ++bx) {
        std::barrier<> bar(TILE * TILE);
        g_bar = &bar;
        std::vector<std::thread> ts;
        for (int ty = 0; ty < TILE; ++ty) for (int tx = 0; tx < TILE; ++tx)
            ts.emplace_back([=]{
                threadIdx_ = {tx,ty,0}; blockIdx_ = {bx,by,0};
                k(TA,TB,M,N,K,AL,A,lda,B,ldb,BE,C,ldc);
            });
        for (auto &t : ts) t.join();
    }
}

static void ref(int TA,int TB,int M,int N,int K,float AL,const float*A,int lda,
                const float*B,int ldb,float BE,float*C,int ldc) {
    for (int i=0;i<M;i++) for (int j=0;j<N;j++) {
        double s=0;
        for (int p=0;p<K;p++) s += (double)(TA?A[p*lda+i]:A[i*lda+p]) * (TB?B[j*ldb+p]:B[p*ldb+j]);
        C[i*ldc+j] = (BE==0.f) ? AL*(float)s : AL*(float)s + BE*C[i*ldc+j];
    }
}

static int check(const char*name,int M,int N,int K,int TA,int TB,float AL,float BE) {
    std::vector<float> A(M*K+K*M), B(K*N+N*K), C0(M*N), C1(M*N), C2(M*N);
    for (auto &v : A) v = (float)((rand()%200)-100)/57.0f;
    for (auto &v : B) v = (float)((rand()%200)-100)/37.0f;
    for (int i=0;i<M*N;i++) { float s=(float)((rand()%100))/11.0f; C0[i]=s; C1[i]=s; C2[i]=s; }
    int lda = TA?M:K, ldb = TB?K:N, ldc = N;
    ref(TA,TB,M,N,K,AL,A.data(),lda,B.data(),ldb,BE,C2.data(),ldc);
    run(gemm_kernel,(N+TILE-1)/TILE,(M+TILE-1)/TILE,TA,TB,M,N,K,AL,A.data(),lda,B.data(),ldb,BE,C0.data(),ldc);
    run(gemm_block_kernel,(N+TILE*4-1)/(TILE*4),(M+TILE*4-1)/(TILE*4),TA,TB,M,N,K,AL,A.data(),lda,B.data(),ldb,BE,C1.data(),ldc);
    double wk=0, wr=0;
    for (int i=0;i<M*N;i++) {
        double sk=std::fabs(C0[i]), sr=std::fabs(C2[i]);
        double rk=std::fabs(C1[i]-C0[i]); rk = sk>1e-3 ? rk/sk : rk;
        double rr=std::fabs(C1[i]-C2[i]); rr = sr>1e-3 ? rr/sr : rr;
        if (rk>wk) wk=rk; if (rr>wr) wr=rr;
    }
    // Against the original kernel the summation order is identical, so the
    // two should agree to within FMA-contraction noise. Against the double
    // reference, float32 error grows with K.
    // Bit-identity with the original kernel is the real criterion: it is the
    // implementation already validated on hardware, and both sum in the same
    // order. The f64 comparison is a loose sanity bound only -- relative error
    // against a double reference is dominated by float32 cancellation.
    bool ok = wk == 0.0 && wr < 2e-3;
    printf("  %-24s M=%-4d N=%-4d K=%-4d TA=%d TB=%d a=%.1f b=%.1f  vs orig %.1e  vs f64 %.1e  %s\n",
           name,M,N,K,TA,TB,AL,BE,wk,wr, ok?"ok":"FAIL");
    return ok?0:1;
}

int main() {
    int bad = 0;
    puts("blocked kernel:");
    bad += check("exact multiple",128,128,64,0,0,1.f,0.f);
    bad += check("ragged M,N,K",100,130,70,0,0,1.f,0.f);
    bad += check("tiny vs 64-tile",17,9,5,0,0,1.f,0.f);
    bad += check("A transposed",96,80,48,1,0,1.f,0.f);
    bad += check("B transposed",96,80,48,0,1,1.f,0.f);
    bad += check("both transposed",70,66,33,1,1,1.f,0.f);
    bad += check("alpha/beta",96,96,40,0,0,0.5f,2.f);
    bad += check("K < TILE",64,64,7,0,0,1.f,0.f);
    puts("more shapes:");
    bad += check("ragged",50,37,23,0,0,1.f,0.f);
    bad += check("transposed",48,32,16,1,1,1.f,0.f);
    printf("%s\n", bad? "FAILURES" : "all passed");
    return bad;
}
